blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://discord.gg/mGwnH4udfv
    about: Please ask questions on our Discord server before opening an issue.
  - name: Discussions
    url: https://github.com/orgs/gitlocalize/discussions
    about: Share ideas, ask questions, and discuss with the community.
  - name: Security Vulnerabilities
    url: https://github.com/gitlocalize/.github/blob/main/SECURITY.md
    about: Please report security vulnerabilities privately via email.
