blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://discord.gg/mGwnH4udfv
    about: Please ask questions on our Discord server before opening an issue.
  - name: Discussions
    url: https://github.com/orgs/gitlocalize/discussions
    about: Share ideas, ask questions, and discuss with the community.
